### PR TITLE
Adding middleware to log al requests

### LINKED ISSUE #9: Include logging service

### PR DESCRIPTION
**Pull request by Alxzu**
**This PR contains:**

- [X] Adding global middleware to log all requests `before` each action controller taking place (basic structure). 

**To be defined:**

- What is the best format/content to put into those logs?
- How to prevent showing sensitive information like `passwords` or `credit card numbers` in the logs. Set up a list of filtered params and replace those in an interceptor? 🤔 

**Notes:**
[Read more about](https://github.com/typestack/routing-controllers#global-middlewares) global middlewares, error handlers, interceptors, etc.

Screen Shot 2020-09-19 at 11 36 09

### CODE REVIEW

**Comment by martinjaimem** [comment]
@Alxzu Nice !!!
Actually I think this PR does the trick 😄 , adding more information like params shouldn't be something we should be doing in prod, the reason behind this is that it doesn't add too much critical information to be used when looking at the production logs. When debugging in production the exception tracking system (Sentry/Exception Hunter) knows the request's context, so if anything goes wrong we will know the request params.
However, it may be nice to have it in development.

**Comment by Alxzu** [comment]
We should add a way of removing logs when `test` environment is on (not all logs, but these ones), letting jest do its job 🤔

**Review by pablanco — APPROVED** [review]
Nice job!

**Comment by alexfradiani** [comment]
> We should add a way of removing logs when `test` environment is on (not all logs, but these ones), letting jest do its job 🤔

I think that we could skip this middleware if running on test environment, but that would require to change a little bit the includes when creating the express server (instead of just loading all files in middlewares), what do you think of this approach? @Alxzu 
I could work on that if you want to complete this feature.

**Review by Alxzu — COMMENTED** [review]
[Take a look at here](https://github.com/typestack/routing-controllers#using-middlewares), I think it would be so much simple to just call `next()` function inside the middleware if the environment is `development`

**Comment by Alxzu** [comment]
> > We should add a way of removing logs when `test` environment is on (not all logs, but these ones), letting jest do its job 🤔
> 
> I think that we could skip this middleware if running on test environment, but that would require to change a little bit the includes when creating the express server (instead of just loading all files in middlewares), what do you think of this approach? @Alxzu
> I could work on that if you want to complete this feature.

**Comment by Alxzu** [comment]
Hey @alexfradiani, thanks for continue with this PR... I think we should add more info inside the logs, I was trying to get some inspiration from Winston and Morgan, but I didn't have the time to continue with this

**Review by alealvarez14 — APPROVED** [review]

**Review by alexfradiani — APPROVED** [review]
Nice

**Pull request merged**
